### PR TITLE
Ruby OOP - Milestone 3 (Game Logic)

### PR DESCRIPTION
**Pull request by teekaytech**
## In this pull request, I have successfully implemented the game_logic level of the Tic-Tac-Toe game (Ruby OOP track of the main curriculum). :standing_man: 
Here are some of the activities carried out:
- I created 2 classes in lib directory, namely: game.rb and player.rb
- I added the complete game logic in the game.rb file. 
- I also added states and behaviors related to players inside the player.rb file.
- The files created are linked to the main.rb file for usability.
- All states and methods created in the logic files were utilized in the main.rb file.
- To my possible best, I followed the DRY rule.

# Kindly review the milestone for merging. :bow:

### CODE REVIEW

**Review by jofer86 — CHANGES_REQUESTED** [review]
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- The project is quite functional at his core and does what it supposed to do, although we have to improve the code just a little bit more.
- In your main.rb file there are a lot of instances were you are using logic related to the board, the better approach would to modularize your main.rb, that file only responsability should be to orchestrate the events, call the events and have them come together, at the current status of your project, there is a lot of board logic placed, maybe you should consider adding the board class to your logic, as it would help with the decoupling process.
- So just that, please make sure you decouple your code in your main.rb file, and make sure his only responsability would be to orchestrate the rest of the classes in order to make the game flow as it should in the code side

--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

**Comment by teekaytech** [comment]
## Thank you, @jofer86 for your time and well-detailed review.
I've fixed the issue you identified and I'm making another review request.
- I was able to create a class consisting of logic for the game board.
- If you observe the main.rb file carefully, its sole purpose is to accept inputs and prints out outputs.

### Kindly review for approval. :bow:

**Comment by lekegitrepo** [comment]
#### Hi @teekaytech :100: :1st_place_medal:
#### You did a good job by implementing the required changes. This project is approved.

### Reviewed by Temitayo Adeleke.

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Pull request merged**
