### PR TITLE
Tic Tac Toe - Milestone 1

### PR DESCRIPTION
**Pull request by teekaytech**
# Hello, 

In this pull request, I have successfully completed the tasks involved in milestone-1 of Tic Tac Toe project. 
- I was able to set up the git-flow as required
- I created the lib directory with .gitkeep file to ensure the file is pushed to the repo
- I also created the lib directory with main.rb file set as executable.

### Kindly review for approval.

### CODE REVIEW

**Review by kobiyoyo — APPROVED** [review]
.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @teekaytech      
#### Great Job so far , but there is one more thing required. 
### General
- [ ] Enable stickler for this project
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by teekaytech** [comment]
## Thank you, @kobiyoyo 

I actually enabled stickler after all the commits.
I've added a new commit to activate the stickler.

### Kindly review for approval.

**Review by pelzolga123 — COMMENTED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great work, congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to development.
_Goodluck in your next milestone_ *Happy coding*

**Pull request merged**
